name: Testing

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: vbence121/projektmunka2_2020:latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        id: make
        run: make
      - name: run testing.sh with test_input.mod
        run: ./Tests/testing.sh test_input.mod
        id: run_test
        if: ${{ steps.make.conclusion == 'success' }}
      - run: diff Tests/exp_json_out.json var.json
        if: ${{ steps.run_test.conclusion == 'success' }}
      - run: diff Tests/exp_output.tex texOutput.tex
      - run: diff Tests/exp_output.html htmlOutput.html
