name: Testing

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get_rapidjson
        run: sudo apt-get install rapidjson-dev 
      - run: make
      - run: cd ./Tests && ./testing.sh test_input.mod
      - run: diff ../Tests/exp_json_out.json ../var.json